DROP TABLE Office CASCADE CONSTRAINTS;
DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE DrivingTest CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE Interview CASCADE CONSTRAINTS;
DROP TABLE Vehicle CASCADE CONSTRAINTS;
DROP TABLE Inspection CASCADE CONSTRAINTS;
DROP TABLE Lesson CASCADE CONSTRAINTS;

CREATE TABLE Office
(
offNo NUMERIC(8,0) CONSTRAINT offNo_PK PRIMARY KEY,
offAddess VARCHAR(50) NOT NULL,
offPostcode NUMERIC(4,0) NOT NULL,
offTelno NUMERIC(8,0) NOT NULL,
staNo NUMERIC(8,0) NOT NULL
);
CREATE TABLE Client
(
cliNo NUMERIC(8,0) CONSTRAINT cliNo_PK PRIMARY KEY,
cliFname VARCHAR(20) NOT NULL,
cliLname VARCHAR(20) NOT NULL,
cliAddress VARCHAR(50) NOT NULL,
cliTelno NUMERIC(8,0) NOT NULL,
cliEmail VARCHAR(20),
cliLicenseNo VARCHAR(8) CONSTRAINT UNIQ_LSCNO UNIQUE CONSTRAINT cliLicenseNo_nn NOT NULL,
cliSex CHAR(1) NOT NULL,
cliDob DATE NOT NULL,
offNo NUMERIC(8,0) NOT NULL,
CONSTRAINT FK_Office_offNo
    FOREIGN KEY (offNo)
    REFERENCES Office(offNo)
    ON DELETE CASCADE
);
CREATE TABLE DrivingTest
(
dtsNo NUMERIC(8,0) CONSTRAINT tesNo_PK PRIMARY KEY,
dtsDate DATE NOT NULL,
dtsLocation VARCHAR(20) NOT NULL,
dtsResult CHAR(1) NOT NULL,
dtsType VARCHAR(20) NOT NULL,
cliNo NUMERIC(8,0) NOT NULL,
CONSTRAINT FK_DrivingTest_cliNo
    FOREIGN KEY (cliNo)
    REFERENCES Client(cliNo)
    ON DELETE CASCADE
);
CREATE TABLE Staff
(
staNo NUMERIC(8,0) CONSTRAINT staNo_PK PRIMARY KEY,
staFname VARCHAR(20) NOT NULL,
staLname VARCHAR(20) NOT NULL,
staJobtitle VARCHAR(20) NOT NULL,
staTelno NUMERIC(8,0) NOT NULL,
staEmail  VARCHAR(20),
staSex CHAR(1) NOT NULL,
staDob DATE NOT NULL,
offNo NUMERIC(8,0) NOT NULL
);
CREATE TABLE Interview
(
cliNo NUMERIC(8,0) NOT NULL,
staNo NUMERIC(8,0) NOT NULL,
intDate DATE NOT NULL,
intComments VARCHAR(50),
CONSTRAINT interview_PK PRIMARY KEY (cliNo, staNo),
CONSTRAINT interview_cliNo_FK FOREIGN KEY (cliNo)
     REFERENCES Client(cliNo)
     ON DELETE CASCADE,
CONSTRAINT interview_staNo_FK FOREIGN KEY (staNo)
     REFERENCES Staff(staNo)
     ON DELETE CASCADE
);
CREATE TABLE Vehicle
(
vehNo NUMERIC(8,0) CONSTRAINT vehNo_PK PRIMARY KEY,
vehModel VARCHAR(20) NOT NULL,
vehMake VARCHAR(20) NOT NULL,
vehColour VARCHAR(20) NOT NULL,
offNo NUMERIC(8,0) NOT NULL,
CONSTRAINT FK_Office_offNo2
    FOREIGN KEY (offNo)
    REFERENCES Office(offNo)
    ON DELETE CASCADE
);
CREATE TABLE Inspection
(
insNo NUMERIC(8,0) CONSTRAINT insNo_PK PRIMARY KEY,
insDate DATE NOT NULL,
insComments VARCHAR(50),
vehNo NUMERIC(8,0),
staNo NUMERIC (8,0),
CONSTRAINT FK_Vehicle_vehNo
    FOREIGN KEY (vehNo)
    REFERENCES Vehicle(vehNo)
    ON DELETE CASCADE,
CONSTRAINT FK_Staff_staNo
    FOREIGN KEY (staNo)
    REFERENCES Staff(staNo)
    ON DELETE CASCADE
);
CREATE TABLE Lesson
(
vehNo NUMERIC(8,0) NOT NULL,
cliNo NUMERIC(8,0) NOT NULL,
staNo NUMERIC(8,0) NOT NULL,
lesDate DATE NOT NULL,
lesStage CHAR(1) NOT NULL,
lesMileagetotal NUMERIC(3,0) NOT NULL,
CONSTRAINT Lesson_PK PRIMARY KEY (vehNo, cliNo, staNo),
CONSTRAINT Lesson_vehNo_FK FOREIGN KEY (vehNo)
     REFERENCES Vehicle(vehNo)
     ON DELETE CASCADE,
CONSTRAINT Lesson_cliNo_FK FOREIGN KEY (cliNo)
     REFERENCES Client(cliNo)
     ON DELETE CASCADE,
CONSTRAINT Lesson_staNo_FK FOREIGN KEY (staNo)
     REFERENCES Staff(staNo)
     ON DELETE CASCADE
);
ALTER TABLE Office
ADD CONSTRAINT FK_Office_staNo
  FOREIGN KEY (staNo)
  REFERENCES Staff(staNo)
  ON DELETE CASCADE;
ALTER TABLE Staff
ADD CONSTRAINT FK_Staff_offNo
  FOREIGN KEY (offNo)
  REFERENCES Office(offNo)
  ON DELETE CASCADE;